### ISSUE TITLE
Zeus vs Wiso/Io edge bugged

### ISSUE THREAD

**Issue by zer11** [onur/DotaBuffCP#14]
Zeus has an extremly high edge against Io/wisp. Dotabuff states that wisp has an edge of 3.39% vs zeus

**Comment by onuraslan** [comment]
I think its because last time I updated database it was different in dotabuff. (*last updated on Fri, 17 Jul 2015 13:26:41 +0300*).

Looks like I have to update regular expressions to update database. I will look into it when I find some free time.

**Comment by onur** [comment]
I believe this issue is resolved, thanks to @aligo our database is updated now.
