### ISSUE TITLE
Awesome work 

### ISSUE THREAD

**Issue by leovarmak** [onur/DotaBuffCP#18]
It is really nice to develop something like this and that too making it open source. I am starting a website and was wondering if I could have a section for this. Though I read the license, I wanted to make sure if I can use it and need your help putting it up on my site.
Seriously, It is people like you who a this world a better place to live !

**Comment by onur** [comment]
Hi. Thank you for kind words :+1: Sure, you can use it anywhere you like.

**Comment by stewhouston** [comment]
Also a big fan of the project :-) It's a change of pace working in perl!

**Comment by iceunicorn** [comment]
Awesome work! I'd like to donate if you can upgrade the version, it's been two monthe and few patches change now! Some data is really out of date.

**Comment by leovarmak** [comment]
Everything is fine but these days I started to find that the data is not up to date. So clearly the application needs a update.

**Comment by onur** [comment]
Alright let me see what I can do

**Comment by leovarmak** [comment]
Thank you :+1:

**Comment by iceunicorn** [comment]
Thank you!

**Comment by onur** [comment]
Ok guys its updated now. Sorry I can't update this more often.

Closing this and #19.
