### ISSUE TITLE
Getting data from dotabuff

### ISSUE THREAD

**Issue by gpt3ch** [onur/DotaBuffCP#24]
Hi, how can I get data from dotabuff as dotabuff does not expose any public API?
Thanks!

**Comment by Guilospanck** [comment]
Hey man. I wrote a python webscrapper to gather those informations. Hope it helps.
https://github.com/Guilospanck/Dota2Counters

**Comment by Guilospanck** [comment]
> Hi, how can I get data from dotabuff as dotabuff does not expose any public API?
> Thanks!

Hey man. I wrote a python webscrapper to gather those informations. Hope it helps.
https://github.com/Guilospanck/Dota2Counters

**Comment by gpt3ch** [comment]
Thanks man! Didn't know about dotabuff counters page
